language: python
env:
  global:
  - DATABASE_URL=sqlite:///db.sqlite3
  - SECRET_KEY=thisisasecret
cache:
  directories:
  - $HOME/.cache/pip
  python:
  - '3.4'
before_install:
- openssl aes-256-cbc -K $encrypted_6c2822a03f14_key -iv $encrypted_6c2822a03f14_iv
  -in deploy_key.enc -out ~/.ssh/id_rsa -d
- openssl aes-256-cbc -K $encrypted_6c2822a03f14_key -iv $encrypted_6c2822a03f14_iv
  -in deploy_staging.sh.enc -out ./deploy_staging.sh -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- chmod 755 ./deploy_staging.sh
install:
- pip install -r requirements.txt
script:
- python src/manage.py migrate --noinput
- cd src; py.test --cov=.
notifications:
  slack: pycontw:Z1FrdUPAMxhG0MjnY8awlRm0
after_success:
- pip install codecov
- cd src; codecov
deploy:
  provider: script
  script: ./deploy_staging.sh
  on:
    branch: feature/travis-ci
