language: python

env:
  - DATABASE_URL=sqlite:///db.sqlite3 SECRET_KEY=thisisasecret
  
cache:
  directories:
    - $HOME/.cache/pip

python:
  - "3.4"

install:
  - pip install -r requirements.txt

script:
  - python src/manage.py migrate --noinput
  - py.test src

